FEDX-651 : Migrate w_dio to GHA
Workiva/w_dio pull request #25
Opened 2024-03-11 12:24 UTC by dustinlessard-wf

### New Pull Request Checklist

- [ ] I have read the [Documentation](https://pub.dev/documentation/dio/latest/)
- [ ] I have searched for a similar pull request in the [project](https://github.com/cfug/dio/pulls) and found none
- [ ] I have updated this branch with the latest `main` branch to avoid conflicts (via merge from master or rebase)
- [ ] I have added the required tests to prove the fix/feature I'm adding
- [ ] I have updated the documentation (if necessary)
- [ ] I have run the tests without failures
- [ ] I have updated the `CHANGELOG.md` in the corresponding package

### Additional context and info (if any)

2024-03-11 12:25 UTC, aviary2-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2024-04-16 21:09 UTC, robbecker-wf requested changes

2024-04-16 21:09 UTC, robbecker-wf commented on .github/workflows/ci.yaml
> +          sudo apt-get clean all
```suggestion
```
We don't need to do any of this in GHA anymore. We can remove the whole build-image job

2024-04-16 21:09 UTC, robbecker-wf commented on .github/workflows/ci.yaml
> +name: CI
Actually now that it exists, let's just use the workflows from https://github.com/Workiva/gha-dart-oss

2024-04-16 21:14 UTC, robbecker-wf commented on .github/workflows/ci.yaml
> +name: CI
Well, actually, those workflows assume dart_dev is installed, so maybe we can't use those here

2024-04-16 21:42 UTC, robbecker-wf commented
I'm not seeing the pub artifacts attached anywhere.

2024-04-16 23:59 UTC, dustinlessard-wf commented on .github/workflows/ci.yaml
> +          path: pub_temp/*
This doesn't seem right.

2024-04-18 04:17 UTC, robbecker-wf commented on .github/workflows/ci.yaml
> +          cd ..
After we install dependencies, can we do the SBOM generation here?

2024-04-18 14:22 UTC, robbecker-wf approved these changes
+10 CI passing, SBOM attached, tests run and attached.

2024-04-18 14:22 UTC, robbecker-wf commented
@Workiva/release-management-p will you merge with WKB still on here? Let's see.

2024-04-18 14:33 UTC, closed without merging